In [2]:
import pandas as pd

df = pd.read_csv(
    "../data/raw/complaints.csv"
)

print(df.shape)

df.head()

/var/folders/td/g0nj9lw14y165dmqgtz9jxzh0000gn/T/ipykernel_13797/3421544982.py:3: DtypeWarning: Columns (0: Consumer disputed?) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

(2505087, 18)

,Date received,Product,Sub-product,Issue,Sub-issue,Consumer complaint narrative,Company public response,Company,State,ZIP code,Tags,Consumer consent provided?,Submitted via,Date sent to company,Company response to consumer,Timely response?,Consumer disputed?,Complaint ID
0,2025-06-20,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Information belongs to someone else,NaN,NaN,Experian Information Solutions Inc.,FL,32092,NaN,NaN,Web,2025-06-20,In progress,Yes,NaN,14195687
1,2025-06-20,Debt collection,Telecommunications debt,Attempts to collect debt not owed,Debt is not yours,NaN,Company can't verify or dispute the facts in t...,"Eastern Account Systems of Connecticut, Inc.",FL,342XX,NaN,NaN,Web,2025-06-20,Closed with explanation,Yes,NaN,14195688
2,2025-06-20,Credit reporting or other personal consumer re...,Credit reporting,Improper use of your report,Reporting company used your report improperly,NaN,NaN,"TRANSUNION INTERMEDIATE HOLDINGS, INC.",AZ,85225,NaN,NaN,Web,2025-06-20,In progress,Yes,NaN,14195689
3,2025-06-20,Credit reporting or other personal consumer re...,Credit reporting,Improper use of your report,Reporting company used your report improperly,NaN,NaN,Experian Information Solutions Inc.,AZ,85225,NaN,NaN,Web,2025-06-20,In progress,Yes,NaN,14195690
4,2025-06-20,Credit reporting or other personal consumer re...,Credit reporting,Incorrect information on your report,Account status incorrect,NaN,NaN,Experian Information Solutions Inc.,IL,60628,NaN,NaN,Web,2025-06-20,In progress,Yes,NaN,14195692

In [ ]:
df.columns.tolist()

['Date received',
 'Product',
 'Sub-product',
 'Issue',
 'Sub-issue',
 'Consumer complaint narrative',
 'Company public response',
 'Company',
 'State',
 'ZIP code',
 'Tags',
 'Consumer consent provided?',
 'Submitted via',
 'Date sent to company',
 'Company response to consumer',
 'Timely response?',
 'Consumer disputed?',
 'Complaint ID']

In [3]:
df["Product"].value_counts()

Product
Credit reporting or other personal consumer reports                             2140547
Debt collection                                                                  119634
Money transfer, virtual currency, or money service                                51228
Credit reporting, credit repair services, or other personal consumer reports      48661
Credit card                                                                       44843
Checking or savings account                                                       42961
Mortgage                                                                          15437
Student loan                                                                      13280
Vehicle loan or lease                                                              9250
Payday loan, title loan, personal loan, or advance loan                            5130
Credit reporting                                                                   3362
Prepaid card                                                                       3357
Credit card or prepaid card                                                        3068
Debt or credit management                                                          2118
Bank account or service                                                            1200
Consumer Loan                                                                       468
Payday loan, title loan, or personal loan                                           365
Payday loan                                                                          94
Money transfers                                                                      74
Other financial service                                                              10
Name: count, dtype: int64

Filter Products

In [4]:
target_products = [
    "Credit card",
    "Payday loan, title loan, personal loan, or advance loan",
    "Checking or savings account",
    "Money transfer, virtual currency, or money service"
]

filtered_df = df[
    df["Product"].isin(target_products)
].copy()

print(filtered_df.shape)
print(filtered_df["Product"].value_counts())

(144162, 18)
Product
Money transfer, virtual currency, or money service         51228
Credit card                                                44843
Checking or savings account                                42961
Payday loan, title loan, personal loan, or advance loan     5130
Name: count, dtype: int64

In [5]:
filtered_df = filtered_df[
    filtered_df["Consumer complaint narrative"].notna()
].copy()

print(filtered_df.shape)

(82067, 18)

In [6]:
filtered_df["Product"].value_counts()

Product
Money transfer, virtual currency, or money service         38424
Checking or savings account                                24383
Credit card                                                16815
Payday loan, title loan, personal loan, or advance loan     2445
Name: count, dtype: int64

Create Product Category Column

In [7]:
product_mapping = {
    "Credit card": "Credit Card",

    "Payday loan, title loan, personal loan, or advance loan":
        "Personal Loan",

    "Checking or savings account":
        "Savings Account",

    "Money transfer, virtual currency, or money service":
        "Money Transfer"
}

filtered_df["product_category"] = (
    filtered_df["Product"]
    .map(product_mapping)
)

In [8]:
filtered_df["product_category"].value_counts()

product_category
Money Transfer     38424
Savings Account    24383
Credit Card        16815
Personal Loan       2445
Name: count, dtype: int64

Clean Complaint Narratives

In [9]:
import re

def clean_text(text):

    text = str(text).lower()

    text = re.sub(r"http\S+", "", text)

    text = re.sub(
        r"[^a-zA-Z0-9\s]",
        " ",
        text
    )

    text = re.sub(
        r"\s+",
        " ",
        text
    )

    return text.strip()

In [10]:
filtered_df["clean_text"] = (
    filtered_df["Consumer complaint narrative"]
    .apply(clean_text)
)

In [11]:
filtered_df[
    [
        "Consumer complaint narrative",
        "clean_text"
    ]
].head()

,Consumer complaint narrative,clean_text
12237,A XXXX XXXX card was opened under my name by a...,a xxxx xxxx card was opened under my name by a...
12532,I made the mistake of using my wellsfargo debi...,i made the mistake of using my wellsfargo debi...
13280,"Dear CFPB, I have a secured credit card with c...",dear cfpb i have a secured credit card with ci...
13506,I have a Citi rewards cards. The credit balanc...,i have a citi rewards cards the credit balance...
13955,b'I am writing to dispute the following charge...,b i am writing to dispute the following charge...

In [12]:
mkdir -p ../data/processed

In [13]:
filtered_df.to_csv(
    "../data/processed/filtered_complaints.csv",
    index=False
)

print("Saved successfully")

Saved successfully

In [ ]:
filtered_df.shape

(82067, 20)

In [5]:
import pandas as pd

df = pd.read_csv("../data/processed/filtered_complaints.csv")

print(df.columns.tolist())

['Date received', 'Product', 'Sub-product', 'Issue', 'Sub-issue', 'Consumer complaint narrative', 'Company public response', 'Company', 'State', 'ZIP code', 'Tags', 'Consumer consent provided?', 'Submitted via', 'Date sent to company', 'Company response to consumer', 'Timely response?', 'Consumer disputed?', 'Complaint ID', 'product_category', 'clean_text']